
const propertyData = [
    {
      id: 1,
      image: "https://codewithsadee.github.io/realvine/assets/images/property-1.jpg",
      title: "10765 Hillshire Ave, Baton Rouge, LA 70810, USA",
      area: "8000sqf",
      beds: 4,
      baths: 4,
      price: "$5000",
      rating: 5.0,
      reviews: 30,
      startingPrice: "Sold Out",
      peraCode: "https://jll-global-gdim-res.cloudinary.com/image/u…/PROD/JLL_Pune_Kohinoor%20Kaleido_8124_CERT_1.jpg",
      description:
        "This luxurious property features an expansive area with modern architecture and all necessary amenities for a comfortable lifestyle.",
      
        projectSummary: {
          name: "Morya Skydale",
          reraNo: "P52100055584",
          developer: "Royal Group",
          parkingType: "Covered",
          nearestLandmark: "Podar International School",
          numberOfFloors: 17,
          landArea: "1.5 Acre",
          ownershipType: "Freehold",
          constructionStage: "Under Construction",
        },
        unitDetails: [
        { type: "2 BHK", size: "807 sqft", price: "Sold Out" },
        { type: "2 BHK", size: "822 sqft", price: "Sold Out" },
        { type: "2 BHK", size: "850 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "1,108 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "1,856 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "2,888 sqft", price: "Sold Out" },
      ],
      facilities: [
        "Gym",
        "Children Play Area",
        "Basket Ball Court",
        "Club House",
        "Power Backup",
        "Swimming Pool",
        "Badminaton Court",
        "Park",
        "Sewage Treatment plant",
        "Vaastu Complaint",
        "Security",
        "Tennis Court",
        "Visitor Parking",
        "Indoor Game Room",
        "Car Parking",
        "Gas Pipeline",
        "Water",
      ],
      
    },
    {
      id: 2,
      image: "https://codewithsadee.github.io/realvine/assets/images/property-2.jpg",
      title: "59345 STONEWALL DR, Plaquemine, LA 70764, USA",
      area: "8000sqf",
      beds: 4,
      baths: 4,
      price: "$5000",
      rating: 5.0,
      reviews: 30,
      startingPrice: "Sold Out",
      description:
        "An elegant property situated in the heart of the city with easy access to major facilities and shopping centers.",
        projectSummary: {
          name: "VTP Flamante",
          reraNo: "P52100051826",
          developer: "VTP Realty",
          parkingType: "Covered",
          phase: "Phase 1",
          numberOfFloors: 33,
          landArea: "10.0 Acre",
          ownershipType: "Freehold",
          constructionStage: "Under Construction",
        },
     
        unitDetails: [
        { type: "2 BHK", size: "696 sqft", price: "Sold Out" },
        { type: "2 BHK", size: "767 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "851 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "989 sqft", price: "Sold Out" },

      ],
      facilities: [
        "Gym",
        "Massage Room",
        "Badminton Court",
        "Basket Ball Court",
        "Wifi",
        "Shopping Center",
        "Gas Pipeline",
        "Vaastu Compliant",
        "Swimming Pool",
        "Security",
        "Tennis Court",
        "Park",
        "Club House",
        "ATM",
        "Indoor Game Room",
        "Car Parking",
        "Steam & Sauna",
        "Children Play Area",
        "Cricket Pitch",
        "Visitor Parking",
        "Intercom",
        "Sewage Treatment Plant",
        "Power Backup",
      ],
    },
    {
      id: 3,
      image: "https://codewithsadee.github.io/realvine/assets/images/property-3.jpg",
      title: "3723 SANDBAR DR, Addis, LA 70710, USA",
      area: "8000sqf",
      beds: 4,
      baths: 4,
      price: "$5000",
      rating: 5.0,
      reviews: 30,
      startingPrice: "Sold Out",
      description:
        "A modern home with spacious interiors and a serene environment, perfect for families.",
       projectSummary: {
          name: "SKYi 5 Maidan",
          reraNo: "P52100050885",
          developer: "Sky Developers",
          parkingType: "Covered",
          numberOfFloors: 22,
          landArea: "5.0 Acre",
          ownershipType: "Freehold",
          constructionStage: "Under Construction",
        },

        unitDetails: [
        { type: "2 BHK", size: "838 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "1,213 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "1,536 sqft", price: "Sold Out" },
      ],
      facilities: [
        "Gym",
        "Children Play Area",
        "Park",
        "Car Parking",
        "Swimming Pool",
        "Badmintion Court",
        "Club House",
        "Security",
        "Cricket Pitch",
        "Indoor Game Room",
      ],
    },
    {
      id: 4,
      image: "https://codewithsadee.github.io/realvine/assets/images/property-4.jpg",
      title: "Lot 21 Royal Oak Dr, Prairieville, LA 70769, USA",
      area: "7500sqf",
      beds: 5,
      baths: 3,
      price: "$7000",
      rating: 4.8,
      reviews: 45,
      startingPrice: "Sold Out",
      description:
        "A contemporary home designed with an open layout, providing ample space and stunning views.",

      projectSummary: {
        name: "Lodha Giardino",
        reraNo: "P521000047587",
        developer: "Lodha Group",
        parkingType: "Covered",
        phase: "Phase 1",
        numberOfFloors: 24,
        landArea: "14.0 Acre",
        ownershipType: "Freehold",
        constructionStage: "Under Construction",
      },
      unitDetails: [
        { type: "2 BHK", size: "867 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "1,381 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "1,844 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "2,158 sqft", price: "Sold Out" },
      ],
      facilities: [
        "Gym",
        "Massage Room",
        "Badminton Court",
        "Basket Ball Court",
        "WiFi",
        "Shopping Center",
        "Gas Pipeline",
        "Vaastu Complaint",
        "Swimming Pool",
        "Security",
        "Tennis Court",
        "Park",
        "Children Play Area",
        "Club House",
        "ATM",
        "Intercom",
        "Indoor Game Room",
        "Visitor Parking",
        "Car Parking",
        "Sewage Treatment Plant",
        "Power Backup",

      ],
    },
    {
      id: 5,
      image: "https://codewithsadee.github.io/realvine/assets/images/property-5.jpg",
      title: "710 Boyd Dr, Unit #1102, Baton Rouge, LA 70808, USA",
      area: "9000sqf",
      beds: 3,
      baths: 3,
      price: "$3000",
      rating: 4.5,
      reviews: 25,
      startingPrice: "Sold Out",
      description:
        "This cozy property is ideal for small families or individuals looking for modern, low-maintenance living.",
      projectSummary: {
        name: "Kohinoor Kaleido",
        reraNo: "P52100046027",
        developer: "Kohinoor Group",
        parkingType: "Covered",
        nearestLandmark: "Podar International School",
        phase: "Phase 1",
        numberOfFloors: 22,
        landArea: "14.0 Acre",
        ownershipType: "Freehold",
        constructionStage: "Under Construction",
      },

      unitDetails: [
        { type: "3 BHK", size: "1,223 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "1,585 sqft", price: "Sold Out" },

      ],
      facilities: [
        "Vaastu Compliant",
        "Massage Room",
        "Badminton Court",
        "Basket Ball Court",
        "WiFi",
        "Shopping Center",
        "Gym",
        "Swimming Pool",
        "Steam & Sauna",
        "Children Play Area",
        "Tennis Court",
        "Cricket Pitch",
        "Park",
        "Club House",
        "Visitor Parking",
        "ATM",
        "Indoor Game Room",
        "Car Parking",
        "Sewage Treatment Plant",
        "Gas Pipeline",
        "Power Backup",

      ],

    },
    {
      id: 6,
      image: "https://codewithsadee.github.io/realvine/assets/images/property-6.jpg",
      title: "5133 Mclain Way, Baton Rouge, LA 70809, USA",
      area: "8200sqf",
      beds: 4,
      baths: 2,
      price: "$4500",
      rating: 4.9,
      reviews: 35,
      startingPrice: "Sold Out",
      description:
        "A spacious family home featuring a large backyard, modern interiors, and easy access to schools and parks.",
      
        projectSummary: {
          name: "Gera Island of Joy",
          reraNo: "P52100052474",
          developer: "Gera Developers Llp's",
          parkingType: "Covered",
          numberOfFloors: 32,
          landArea: "13.0 Acre",
          ownershipType: "Freehold",
          constructionStage: "Under Construction",
        },
        unitDetails: [
        { type: "2 BHK", size: "607 sqft", price: "Sold Out" },
        { type: "2 BHK", size: "857 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "928 sqft", price: "Sold Out" },
        { type: "3 BHK", size: "1,299 sqft", price: "Sold Out" },
        { type: "4 BHK", size: "1,673 sqft", price: "Sold Out" },
      ],

      facilities: [
        "Gym",
        "Swimming Pool",
        "Steam & Sauna",
        "Massage Room",
        "Children Play Area",
        "Badminton Court",
        "Tennis Court",
        "Basket Ball Court",
        "Cricket Pitch",
        "Park",
        "Club House",
        "Visitor Parking",
        "WiFi",
        "Intercom",
        "Shopping Center",
        "ATM",
        "Power Backup",
        "Indoor Game Room",
        "Car Parking",
        "Sewage Treatment Plant",
        "Vaastu Compliant",
      ],
    },

  ];

  export default propertyData;